### PR TITLE
Add example of deploying serverless functions with Vercel.

### PR DESCRIPTION
**Pull request by leerob**
Hey! Cheers on the course launch. Following up from Twitter 😄 

I went ahead and converted the existing `/functions` to a Vercel-compatible `/api` folder. To deploy:

- Run `vercel` from the `gatsby` folder.
- That's it! It deploys the Gatsby app as well as the `/api` folder.

Here's a live example -> https://slicks-slices.vercel.app/api/hello

### CODE REVIEW

**Comment by wesbos** [comment]
thanks @leerob  - the nodemailer dep, Does that need to be in the main package.json instead of the function's package?

**Comment by leerob** [comment]
Yeah, that's typically the setup we recommend. This way you can run `vercel` and it deploys both the Gatsby site and API routes with zero-config.

Side note: I don't have access to the env vars so I wasn't able to test sending an email. Please give that a test before merging 😄  Should work the same as Netlify, though!

**Comment by wesbos** [comment]
Will do -thanks for your help on this!

**Comment by leerob** [comment]
Closing as stale, but happy to revisit this if you'd like 😄

**Pull request closed without merging**
